Feature/category
dansenpir/owlrangenotes-backend pull request #16
Opened 2022-10-25 20:16 UTC by EricOliveiras

Add module category

2022-10-26 13:39 UTC, dansenpir requested changes

2022-10-26 13:39 UTC, dansenpir commented on src/middlewares/category/index.ts
> +    if(!id) {
Esse if deveria estar aninhado?

2022-10-26 14:59 UTC, EricOliveiras commented on src/middlewares/category/index.ts
> +    if(!id) {
resolvido

2022-10-27 02:49 UTC, viniciuscosmome commented on src/modules/category/useCase/DeleteCategory.ts
> +    if (category?.id_student !== id_student) {
Como o método "findOneById" busca somente valores que contenham exatamente os valores de "id" e "id_student ", e o retorno traz um objeto com seus valores ou null, você pode simplificar a verificação com esta mudança.

```suggestion
    if (!category) {
```

2022-10-27 11:53 UTC, EricOliveiras commented on src/modules/category/useCase/DeleteCategory.ts
> +    if (category?.id_student !== id_student) {
Resolvido

2022-10-27 13:24 UTC, viniciuscosmome approved these changes

2022-10-27 13:42 UTC, dansenpir approved these changes
LGTM

2022-10-27 13:44 UTC, merged